---
- hosts: test_docker
  remote_user: root
  tasks:
  - name: docker pull netdata/netdata
    shell: docker pull  netdata/netdata:v1.18.1
  - name: start netdata
    shell: docker run -d  --restart=always --name=netdata -p 19999:19999 -v /etc/passwd:/host/etc/passwd:ro  -v /etc/group:/host/etc/group:ro -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /var/run/docker.sock:/var/run/docker.sock:ro --cap-add SYS_PTRACE --security-opt apparmor=unconfined netdata/netdata:v1.18.1

